### ISSUE TITLE
implement properties.timeout for account().tokens.add(properties)

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server-api#18]
`properties.timeout` is optional and defaults to `7200` (2h in seconds). 

If token is expired, then `sessions.add({token: 'expiredtoken123'})` should reject with `404 token expired`

**Comment by Taekyoon** [comment]
Can I do this issue?!

**Comment by gr2m** [comment]
maybe finish https://github.com/hoodiehq/hoodie-account-server-api/issues/17 first :) but sure, all yours, let me know if you need any help

**Comment by Taekyoon** [comment]
@gr2m I'll assign this issue to @vkai. And I'll work together with him. Is it fine?

**Comment by gr2m** [comment]
sure thing 👍

**Comment by gr2m** [comment]
I’ve invited you both to Hoodie’s contributors team. You can accept it at https://github.com/hoodiehq

**Comment by Taekyoon** [comment]
@gr2m @vkai Hey Greg, we just added some code to figure out this issue on Wednesday, but we didn't make test code. The reason is we have no idea where we should put code in the project. Where do we put the test code in this proejct? 

p.s) In issue #17 I already added `tokens-test.js` to test validating `token.type'.

**Comment by gr2m** [comment]
I’ve merged #36 now, you can add tests for this to `tokens-test.js`, too

**Comment by Taekyoon** [comment]
@gr2m Thanks Greg!
